### ISSUE TITLE
Course endpoint returns misnamed field

### ISSUE THREAD

**Issue by devsdevsdevs** [icssc-projects/peterportal-public-api#12]
`/courses/{courseID}` endpoint returns a field called `dependencies`. This implies that listed courses are prerequisites rather the class is a prerequisite for these courses. I think the field should be renamed to `prerequisite_for`.

**Comment by uci-mars** [comment]
Plan for fix deployment (to be completed in order):

- [ ] @chenaaron3 to change the field key on all course item and re-index into ES.
- [ ] @ramanxg to run the JS script `/refreshESCache.js` in util to refresh the ES data cache
- [ ] @ramanxg to update the doc
- [ ] @uci-mars to deploy a new build once fix is completed

**Comment by ChaseC99** [comment]
GraphQL schema will also need to be updated when this is renamed.

**Comment by uci-mars** [comment]
@chenaaron3 @ramanxg follow up on this?

**Comment by chenaaron3** [comment]
Done.
