### ISSUE TITLE
Add color to the different responses for each response in documentation

### ISSUE THREAD

**Issue by ramanxg** [icssc-projects/peterportal-public-api#17]
![image](https://user-images.githubusercontent.com/9029237/101119746-dafd3980-35a0-11eb-8a99-c2d53588e67a.png)
Currently colors are the same, could be helpful and more interesting to the eye to add color.

**Comment by nananananate** [comment]
gotcha!

**Comment by nananananate** [comment]
## 📝 Note for those who may need to change this in the future

Changing colors and titles of these `admonitions` can be found in the [documentation of mkdocs-material](https://squidfunk.github.io/mkdocs-material/reference/admonitions/)
