### ISSUE TITLE
Other Disclaimer Grammar

### ISSUE THREAD

**Issue by ramanxg** [icssc-projects/peterportal-public-api#175]
In the `Other Disclaimer` on the home page, it should be `strive` not `stride`. 

> Although we consolidate our data directly from official UCI sources, this application is by all means, not an official UCI tool. We ~stride~ strive to keep our data as accurate as possible with the limited support we have from UCI. Please take that into consideration while using this API.

**Comment by kirbster6** [comment]
I got this one!
