### ISSUE TITLE
Summer Session course codes reported as waitlist count

### ISSUE THREAD

**Issue by ecxyzzy** [icssc-projects/peterportal-public-api#189]
When querying the API's Schedule of Classes endpoint for Summer Session courses, the course codes are also reported as the number of students on the waitlist for that course. This is probably due to the fact that those courses don't seem to have waitlists; as shown below, WebSoc omits the "WL" column entirely for Summer Session courses.

Example query:
```sh
% curl "https://api.peterportal.org/rest/v0/schedule/soc?term=2022%20Summer2&department=I%26C%20SCI&courseNumber=6B"
```
Response (`courses` object only):
```json5
{
	"courses": [{
		"deptCode": "I&C SCI",
		"courseComment": "",
		"prerequisiteLink": "",
		"courseNumber": "6B",
		"courseTitle": "BOOL LOG & DISC STR",
		"sections": [{
				"sectionCode": "36520",
                                ...
				"numOnWaitlist": "36520",
                                ...
			},
			{
				"sectionCode": "36521",
                                ...
				"numOnWaitlist": "36521",
                                ...
			}
		]
	}]
}
```
The same query on WebSoc:
![image](https://user-images.githubusercontent.com/89349085/160509606-ae38a0bf-8cef-4a13-862a-27f5c7571248.png)

**Comment by ChaseC99** [comment]
That's a big waitlist lmao

**Comment by ramanxg** [comment]
This will be a fix for the [websoc-api](https://github.com/icssc-projects/websoc-api). Since we just use that directly.
