### ISSUE TITLE
Create CI/CD pipeline for deploying.

### ISSUE THREAD

**Issue by ramanxg** [icssc-projects/peterportal-public-api#46]
Set up a CI/CD pipeline. Github actions to test the every pull request and merge to master. 

- Update the tests for REST
- Research how to set it up, whether through github action, Travis, or other. 
- More...

**Comment by nananananate** [comment]
- [ ] Run multi-platform tests via Travis
- [ ] Get coverage badge from Travis
- [ ] Implement code quality scanning (probably via [codefactor.io](https://www.codefactor.io/)
- [ ] CD Pipeline for deployment to Heroku or AWS Lambda

**Comment by ramanxg** [comment]
Closing for #81
