### ISSUE TITLE
GPA calculation is off on grades

### ISSUE THREAD

**Issue by uci-mars** [icssc-projects/peterportal-public-api#47]
cc: @Maybe14 

> i've been noticing a lot of data variability between mine and peterportal's api
> 
> i know for the instructors, you used the column that i scraped from websoc rather than the original, but the gpa is really different...
> 
> my guess is that you guys included the p/np in the calculation

**Comment by ramanxg** [comment]
I see the issue with the grades and why the calculation is off. I am going to switch which professor column the sqlite db uses so the right courses are averaged. This also actually changes the format of the instructor name for the grades methods, and regex and docs have to be updated.

- [ ] Update sqlite script and db
- [ ] Update instructor regex for grades helper
- [ ] Change docs for new instructor pattern
