### ISSUE TITLE
Update Tests for REST

### ISSUE THREAD

**Issue by ramanxg** [icssc-projects/peterportal-public-api#49]
The current tests from jest are outdated, and also needs updating for the new features added. 

Main Tests that need to be updated:
- Grades (Add unit tests for the grades helper methods)
- API key authentication
  - Test Cases:
    - Valid API Key
    - Invalid API Key
    - Invalid header
    - No headers in request 
- Websoc api
  - Correct API calls 
  - Invalid parameters
  - Correct data in Response

On branch `unit-tests`, there is an update to the tests that separates the different tests into separate files. Start working from this branch to update the REST tests.

**Comment by ChaseC99** [comment]
#51 includes some changes to REST test
- Updates old data discrepancies in the expected output
- Enables Integration test for development environment
