### ISSUE TITLE
SSL Error on REST API courses endpoint

### ISSUE THREAD

**Issue by devsdevsdevs** [icssc-projects/peterportal-public-api#52]
Sending a GET request to the endpoint at `https://api.peterportal.org/rest/v0/courses/CHEM1A` for instance throws an error, 
`Error: write EPROTO 3179117272:error:10000438:SSL routines:OPENSSL_internal:TLSV1_ALERT_INTERNAL_ERROR:../../third_party/boringssl/src/ssl/tls_record.cc:592:SSL alert number 80` according to Postman. We are using x-api-key header with an API key generate for AntAlmanac, for reference.

Edit: Sending the request on http as in `http://api.peterportal.org/rest/v0/courses/CHEM1A` works fine

**Comment by ChaseC99** [comment]
Our Heroku was downgraded to the free tier, which doesn’t allow SSL certificates. Hoping to get SSL back when we switch to serverless!

**Comment by jwagh3610** [comment]
6890880:error:10000438:SSL routines:OPENSSL_internal:TLSV1_ALERT_INTERNAL_ERROR:..\..\third_party\boringssl\src\ssl\tls_record.cc:592:SSL alert number 80
