### ISSUE TITLE
Follow guidelines of UCI Directory Privacy Policy

### ISSUE THREAD

**Issue by ramanxg** [icssc-projects/peterportal-public-api#62]
Privacy Policy:

> This directory has been compiled for the use and convenience of the faculty, staff, students, and affiliates of the University of California, Irvine and others dealing with UC Irvine. It is the property of the Regents of the University of California. In accordance with the California Information Practices Act, neither this directory nor the information contained herein may be used, rented, distributed, or sold for commercial purposes. Compilation or redistribution of information from this directory is strictly forbidden. Upon using this directory, you submit to these terms of use. For more details, please see the University guidelines for assuring the privacy of personal information in mailing lists and telephone directories.

We should follow the privacy policy, so we do not get in trouble, and the API can continue to be used. I would consider at least removing the phone number since, that's the most sensitive information. Most other fields for instructors can be found from their own websites or other pages.

Things to do:
- update elastic search db
  - This can be a simple run of `npm refresh`
- Update graphql schema
  - We wil need to remove the phone number field from Instructor types.
- change documentation that includes phone
  - Change any examples in the documentation that show the phone number, this is probably in the REST docs for instructors.
  - Remove any mention of compiling from UCI Directory like in below comment.
  - Rebuild docs

**Comment by ChaseC99** [comment]
![image](https://user-images.githubusercontent.com/29494270/110867965-8a226e80-827c-11eb-9f87-97a22d236e7f.png)
Also need to remove mention of the directory from our website.

**Comment by ramanxg** [comment]
The phones in the elasticsearch have now been removed from the professors information.
