### ISSUE TITLE
Fix average GPA calculations with P/NP

### ISSUE THREAD

**Issue by ramanxg** [icssc-projects/peterportal-public-api#95]
As mentioned by Mr. Zotistics, there are errors in the average gpa calculation, and we can fix them by excluding p/np on those calculations. We will probably add a parameter to the request, and also investigate why the gpa calculation is different.

**Comment by Edwu29** [comment]
- [ ] Updating SQL query
- [ ] Changing REST API to take extra query parameter passOrNoPass
- [ ] Changing GraphQL API
- [ ] Updating Documentation
